myproject/urls.py
from django.contrib import admin
from django.urls import path
from myapp.views import LoginView,LogoutView,AdduploadView,UploadReadView,UpdateView,DeleteView,DetailView,Home,AdminRegisterView,admin_dashboard_view,Intro,AnnouncementView,AnnounceReadView,AnounceUpdateView,AnDeleteView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('adminregister/',AdminRegisterView.as_view(),name='adminsignin'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('upload/',AdduploadView.as_view(),name='create'),
    path('viewuploads/',UploadReadView.as_view(),name='uploadlist'),
    path('uploadsupdate/<int:pk>',UpdateView.as_view(),name='update'),
    path('uploaddelete/<int:pk>',DeleteView.as_view(),name='delete'),
    path('detail/<int:id>/',DetailView.as_view()),
    path('',Home.as_view()),
    path('dashboard/', admin_dashboard_view, name='admin_dashboard'),
    path('home/',Intro.as_view(),name='home'),
    path('announcement/',AnnouncementView.as_view(),name='announcement'),
    path('anread/',AnnounceReadView.as_view(),name='read'),
    path('Anuploadsupdate/<int:pk>',AnounceUpdateView.as_view(),name='anupdate'),
    path('Anddelete/<int:pk>',AnDeleteView.as_view(),name='andelete'),
    
] 

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

from django import forms

from django.utils import timezone

from django.contrib.auth.models  import User

from django.core.exceptions import ValidationError

class Dashboard(models.Model):

    Filetype = models.CharField(choices=[('image','image'),('videos','videos'),('files','files'),('gif','gif'),('link','link')],max_length=100)

    Uploaded_date = models.DateTimeField(default=timezone.now)

    User_id = models.ForeignKey(User,on_delete=models.CASCADE)

    File = models.FileField(upload_to='uploads/',null=True,blank=True)

    link = models.URLField(blank=True,null=True)

    def __str__(self):
        return self.Filetype
    

    def clean(self):
        
        if self.File and self.link:
            
            raise forms.ValidationError("Please provide either a video file or a video link, not both.")

class Announcements(models.Model):

    title = models.CharField(max_length=100)

    message = models.TextField(max_length=100)

    uploaded_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

        
    

myapp/forms.py
from django import forms

from myapp.models import Dashboard,User,Announcements

class AdminRegistrationForm(forms.ModelForm):

    class Meta:

        model = User

        fields = ['username','password']

        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control mx-auto','placeholder':'enter your username','style':'border:2px solid black;width:300px'}),
            'password':forms.PasswordInput(attrs={'class':'form-control mx-auto','placeholder':'enter your password','style':'border:2px solid black;width:300px'})
                                                  
            }

# class LoginForm(forms.Form):

#     username = forms.CharField(max_length=100, widget = forms.TextInput(attrs={'class':'form-control mx-auto','placeholder':'enter your username','style':'border:2px solid black;width:300px'}))
           

#     password = forms.CharField(max_length=50, widget = forms.PasswordInput(attrs={'class':'form-control mx-auto','placeholder':'enter your username','style':'border:2px solid black;width:300px'}))
           


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        label="Username",
        widget=forms.TextInput(attrs={
            'class': 'form-control mx-auto',
            'id': 'floatingUsername',
            'placeholder': 'Username'
        })
    )
    password = forms.CharField(
        max_length=50,
        label="Password",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'id': 'floatingPassword',
            'placeholder': 'Password',
            'autocomplete': 'new-password' 
        })
    )
   

class UploadForm(forms.ModelForm):

    class Meta:

        model = Dashboard

        fields = ['Filetype','File','link']

        widgets = {
            'Filetype': forms.Select(
                attrs={
                    'class': 'form-select',
                    'placeholder': 'Select file type'
                }
            ),
            'File': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'link' : forms.URLInput(
                attrs={
                    'class': 'form-control',
                    'placeholder':'paste any youtube or videolink'
                }
            )
        }
    
    def clean(self):
        cleaned_data = super().clean()
        video = cleaned_data.get("File")
        link = cleaned_data.get("link")

        if video and link:
            raise forms.ValidationError("Please upload a video or add a link, not both.")

class AnnouncementForm(forms.ModelForm):

    class Meta:

        model = Announcements

        fields = ['title','message']

myapp/views.py
from django.shortcuts import render,redirect

from django.http import HttpResponseForbidden

from django.views.generic import View

from myapp.forms import AdminRegistrationForm,LoginForm,UploadForm,AnnouncementForm

from myapp.models import User,Dashboard,Announcements

from django.contrib.auth import authenticate,login,logout

from django.utils.dateparse import parse_date

from django.contrib.auth.decorators import login_required,user_passes_test



def is_admin_user(user):
    
    return user.is_authenticated and user.username == 'admin'

@login_required
@user_passes_test(is_admin_user)
def admin_dashboard_view(request):
    return render(request, 'admin_dashboard.html')

# # Ensure the fixed admin exists
# def ensure_admin_exists():
    
#     if not User.objects.filter(username='admin').exists():
        
#         User.objects.create_user(username='admin', password='admin123')


class AdminRegisterView(View):

    def get(self,request):

        form = AdminRegistrationForm

        return render(request,'Signup.html',{'form':form})
    
    def post(self,request):

        form =AdminRegistrationForm(request.POST)

        if form.is_valid():

            username = form.cleaned_data.get('username')

            password = form.cleaned_data.get('password')
            
            User.objects.create_user(username=username,password=password)


        return render(request,'Signup.html',{'form':form})

        return redirect('login')
    
class LoginView(View):

    def get(self,request):

        # ensure_admin_exists()

        form = LoginForm

        return render(request,'Login.html',{'form':form})
    
    def post(self,request):

        form = LoginForm(request.POST)

        if form.is_valid():

            username = 'admin'

            password = form.cleaned_data.get('password')

            
            user_obj = authenticate(request,username=username,password=password)

            if user_obj is not None and user_obj.username == 'admin':

                login(request,user_obj)

                return redirect('admin_dashboard')
            
            else:
                return render(request, 'login.html', {
                    'form': form,
                    'login_failed': True
                })

        return render(request, 'login.html', {'form': form})
    
            
class LogoutView(View):

    def get(self,request):

        logout(request)

        return redirect('login')
    
class AdduploadView(View):

    def get(self,request):

        if not is_admin_user(request.user):
            
            return HttpResponseForbidden("You are not authorized.")

        form = UploadForm

        return render(request,'Adduploads.html',{'form':form})
    
    def post(self,request):

        if not is_admin_user(request.user):
            
            return HttpResponseForbidden("You are not authorized.")

        form = UploadForm(request.POST,request.FILES)

        if form.is_valid():

            Dashboard.objects.create(User_id=request.user,**form.cleaned_data)

            return redirect('create')

        return render(request,'Adduploads.html',{'form':form})
    
class UploadReadView(View):

    def get(self,request):

        items = Dashboard.objects.all()

        return render(request,'uploads.html',{'items':items})
    
class UpdateView(View):

    def get(self,request,**kwargs):

    #  if not is_admin_user(request.user):

        id = kwargs.get('pk')

        item = Dashboard.objects.get(id=id)

        form = UploadForm(instance=item)

        return render(request,'update.html',{'form':form})
    
    def post(self,request,**kwargs):

    #  if not is_admin_user(request.user):

        id = kwargs.get('pk')


        item = Dashboard.objects.get(id=id)

        form = UploadForm(request.POST,request.FILES, instance=item)

        if form.is_valid():

            form.save()

        form = UploadForm

        return render(request,'update.html',{'form':form})
    
class DeleteView(View):

    def get(self,request,**kwargs):

    #  if not is_admin_user(request.user):

        id = kwargs.get('pk')

        Dashboard.objects.get(id=id).delete()

        return redirect('uploadlist')
    
class DetailView(View):

    def get(self,request,**kwargs):

        id = kwargs.get('id')

        item = Dashboard.objects.get(id=id)

        return render(request,'detail.html',{'item':item})
    
# class SearchView(View):

#     def get(self,request,**kwargs):

#         date = request.GET.get('date')

#         item = []

#         if date :

#             parse_dt = parse_date(date)
            
#             if parse_dt:

#                 item = Dashboard.objects.filter(Uploaded_date = parse_dt)

        

#         return render(request,'search.html',{'item':item,'query':date})

class Home(View):

    def get(self,request):

        return render(request,'base.html')


class Intro(View):

    def get(self,request):

        return render(request,'home.html')
    
class AnnouncementView(View):

    def get(self,request):

        # if not is_admin_user(request.user):

             
            

        form = AnnouncementForm

        return render(request,'Announcement.html',{'form':form})
    
    def post(self,request):
        
        # if not is_admin_user(request.user):
            
        #     return HttpResponseForbidden("You are not authorized.")
        
        form = AnnouncementForm(request.POST)

        if form.is_valid():

            title = form.cleaned_data.get('title')

            message = form.cleaned_data.get('message')

            Announcements.objects.create(title=title,message=message)

            return redirect('announcement')

        return render(request,'Announcement.html',{'form':form})
    
class AnnounceReadView(View):

    def get(self,request):

        items = Announcements.objects.all().order_by('uploaded_date')

        return render(request,'announceuploads.html',{'items':items})

class AnounceUpdateView(View):

    def get(self,request,**kwargs):

    #  if not is_admin_user(request.user):

    #     return HttpResponseForbidden("You are not authorized.")

     id = kwargs.get('pk')

     item = Announcements.objects.get(id=id)

     form = AnnouncementForm(instance=item)

     return render(request,'Anupdate.html',{'form':form})
    
    def post(self,request,**kwargs):

    #  if not is_admin_user(request.user):

    #     return HttpResponseForbidden("You are not authorized.")

     id = kwargs.get('pk')
     
     item = Announcements.objects.get(id=id)

     form = AnnouncementForm(request.POST,request.FILES, instance=item)

     if form.is_valid():

            form.save()

        # form = AnnouncementForm

     return render(request,'announceuploads.html',{'form':form})
    
class AnDeleteView(View):

    def get(self,request,**kwargs):

    #  if not is_admin_user(request.user):

    #     return HttpResponseForbidden("You are not authorized.")

     id = kwargs.get('pk')

     Announcements.objects.get(id=id).delete()

     return redirect('read')
    

            

myapp/templates/Adduploads.html
{% extends 'base.html' %}


{% block content %}
<style>
    
  .upload-form-container {
    max-width: 600px;
    margin: 10rem auto;
    padding: 4rem;
    border-radius: 25px;
    background: rgba(185, 189, 178, 0.15);
    box-shadow: 0 8px 32px 0 rgba(201, 63, 189, 0.37);
    backdrop-filter: blur(8px);
    -webkit-backdrop-filter: blur(8px);
    border: 1px solid rgba(255, 255, 255, 0.18);
    animation: pulse-glow 3s infinite alternate;
    background-color: #f32843;
    width: 100%;
    
  }
  

  @keyframes pulse-glow {
    0% {
      box-shadow: 0 0 15px rgba(255, 255, 255, 0.2);
    }
    100% {
      box-shadow: 0 0 30px rgba(255, 255, 255, 0.5);
    }
  }

  .upload-form-container label {
    color: #fff;
    font-weight: bold;
  }

  .upload-form-container input,
  .upload-form-container select {
    border-radius: 15px;
  }

  .fancy-button {
    background: linear-gradient(45deg, #ff6b6b, #f8e71c, #32cd32, #1e90ff);
    background-size: 300% 300%;
    color: white;
    font-weight: bold;
    border: none;
    padding: 0.75rem 1.5rem;
    border-radius: 30px;
    transition: background-position 0.5s ease-in-out;
    animation: gradient-move 5s ease infinite;
    text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
  }

  .fancy-button:hover {
    background-position: right center;
    transform: scale(1.05);
  }

  @keyframes gradient-move {
    0% {
      background-position: 0% 50%;
    }
    50% {
      background-position: 100% 50%;
    }
    100% {
      background-position: 0% 50%;
    }
  }
</style>

<div class="upload-form-container">
  <h3 class="text-center text-white mb-4">Upload Your File</h3>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_Filetype"  class="form-label">File Type </label>
      {{ form.Filetype }}
    </div>
    <div class="mb-3">
      <label for="id_File" class="form-label">Choose File</label>
      {{ form.File }}
    </div>
    <div class="mb-3">
      <label for="{{form.link.id_for_label}}" class="form-label">Youtube or Video link</label>
      {{ form.link }}
    </div>


    
    <div class="text-center">
      <button type="submit" class="fancy-button">Upload</button>
    </div>
  </form>
</div>
{% endblock %}

 <!-- Footer -->
  
  <footer>
    <i class="text-white me-2">© 2025 Ward 12 Dashboard. All rights reserved.</i>
  </footer>
  
</body>
</html>

myapp/templates/Announcement.html
{% extends 'base.html' %}

{% block title %}
<title>📢 Post Announcement</title>
{% endblock %}

{% block content %}
<style>
  html, body {
    margin: 0;
    padding: 0;
    height: 100%;
    background: linear-gradient(135deg, #ff9966, #ff5e62,#fcff5e);
    font-family: 'Segoe UI', Tahoma, sans-serif;
  }

  .page-wrapper {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    background: linear-gradient(135deg, #e75208, #e98de1,#ff5e62);
  }

  .announcement-section {
    flex-grow: 1;
    display: flex;
    justify-content: center;
    align-items: flex-start;
    padding: 20px;
    margin-top: 150px; /* Ensures gap from navbar */
  }

  .announcement-form {
    background: #fff;
    padding: 1rem 1rem; /* Compact padding */
    border-radius: 12px;
    box-shadow: 0 5px 18px rgba(255, 94, 98, 0.25);
    max-width: 420px;
    width: 100%;
  }

  .announcement-form h2 {
    text-align: center;
    color:  #be184a;
    margin-bottom: 1rem;
    font-size: 1.5rem;
  }

  .form-group {
    margin-bottom: 0.8rem;
  }

  label {
    display: block;
    margin-bottom: 0.4rem;
    color: #0f0e0e;
    font-weight: 600;
    font-size: 0.95rem;
  }

  input[type="text"],
  textarea {
    width: 100%;
    padding: 0.55rem 0.85rem;
    border-radius: 8px;
    border: 1.5px solid  #be184a;
    font-size: 0.95rem;
    font-family: inherit;
    color: #0a0909;
  }

  input:focus,
  textarea:focus {
    border-color: #ff5e62;
    outline: none;
    box-shadow: 0 0 5px rgba(255, 94, 98, 0.4);
  }

  textarea {
    resize: vertical;
    min-height: 80px;  /* Reduced height */
    max-height: 120px;
  }

  .btn-submit {
    margin-top: 1rem;
    background-color: #be184a;
    color: white;
    font-weight: 600;
    border: none;
    padding: 0.6rem 1rem;
    border-radius: 25px;
    width: 100%;
    cursor: pointer;
    transition: 0.3s ease;
    
  }

  .btn-submit:hover {
    background-color: #e54455;
    transform: scale(1.03);
  }

  
</style>

<main class="page-wrapper">
  <div class="announcement-section">
    <form method="post" class="announcement-form">
      {% csrf_token %}
      <h2>📣 Post Announcement</h2>

      <div class="form-group">
        {{ form.title.label_tag }}
        {{ form.title }}
      </div>

      <div class="form-group">
        {{ form.message.label_tag }}
        {{ form.message }}
      </div>

      <button type="submit" class="btn-submit">Submit</button>
    </form>
  </div>

  
</main>
{% endblock %}

myapp/templates/Anupdate.html
{% extends 'uploads.html' %}

{% block title %}
  <title>Announcement Gallery - Ward12</title>
{% endblock %}

{% block content %}
<div class="container mt-5" style="max-width: 750px;">
  <h2 class="text-center mb-4">✏️ Update Announcement</h2>

  {% if request.user.is_staff %}
    <form method="POST" enctype="multipart/form-data" class="bg-light p-4 rounded shadow">
      {% csrf_token %}
      {{ form.as_p }}

      <div class="d-flex justify-content-between mt-4">
        <button type="submit" class="btn btn-sucess">✅ Update</button>
        <a href="{% url 'delete' form.instance.pk %}" class="btn btn-danger"
           onclick="return confirm('Are you sure you want to delete this announcement?');">🗑️ Delete</a>
      </div>
    </form>
  {% else %}
    <div class="alert alert-danger text-center mt-4">
      ❌ You do not have permission to edit or delete this announcement.
    </div>
  {% endif %}
</div>
{% endblock %}

myapp/templates/Signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Admin Signup - Ward 12 Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet" />

  <style>
    body {
      background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      font-family: 'Segoe UI', sans-serif;
    }

    .card {
      border: none;
      border-radius: 1rem;
      box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
      padding: 2rem;
      max-width: 420px;
      width: 100%;
      background: white;
    }

    .card h3 {
      color: #007bff;
      font-weight: bold;
    }

    .form-control {
      border-radius: 0.5rem;
      border: 2px solid #ced4da;
      transition: all 0.3s ease;
    }

    .form-control:focus {
      border-color: #007bff;
      box-shadow: 0 0 8px rgba(0, 123, 255, 0.25);
    }

    .btn-custom {
      background-color: #007bff;
      color: white;
      border-radius: 0.5rem;
      transition: 0.3s ease;
    }

    .btn-custom:hover {
      background-color: #0056b3;
    }

    .icon {
      font-size: 1.2rem;
      margin-right: 0.5rem;
    }
  </style>
</head>
<body>

  <div class="card">
    <h3 class="text-center mb-4"><i class="fas fa-user-shield icon"></i>Admin Signup</h3>

    <form method="POST">
      {% csrf_token %}
      
      <div class="mb-3">
        {{ form.username.label_tag }}
        {{ form.username }}
        {% for error in form.username.errors %}
          <div class="text-danger small">{{ error }}</div>
        {% endfor %}
      </div>

      <div class="mb-3">
        {{ form.password.label_tag }}
        {{ form.password }}
        {% for error in form.password.errors %}
          <div class="text-danger small">{{ error }}</div>
        {% endfor %}
      </div>

      <button type="submit" class="btn btn-custom w-100">Signin</button>
    </form>

    <div class="text-center mt-3">
      Already have an account? <a href="{% url 'login' %}" class="text-primary fw-bold">Login</a>
    </div>
  </div>

</body>
</html>

myapp/templates/admin_dashboard.html
{% extends 'base.html' %}
{% block title %}<title>Admin Dashboard</title>{% endblock %}

{% block content %}
<style>
  .dashboard-card {
    margin: 80px auto;
    max-width: 600px;
    padding: 2rem;
    background: linear-gradient(to right, #6dd5ed, #2193b0);
    border-radius: 15px;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
    color: #fff;
    text-align: center;
  }

  .dashboard-card h2 {
    margin-bottom: 1.5rem;
    font-weight: bold;
  }

  .dashboard-btn {
    margin: 0.5rem;
    padding: 0.75rem 2rem;
    border: none;
    border-radius: 25px;
    background: white;
    color: #2193b0;
    font-weight: bold;
    transition: 0.3s ease;
    text-decoration: none;
    display: inline-block;
  }

  .dashboard-btn:hover {
    background: #fff;
    color: #0f2027;
    box-shadow: 0 0 12px #00c9ff;
  }

  .logout-btn {
    margin-top: 1rem;
    display: inline-block;
    background: #dc3545;
    color: white;
    padding: 0.6rem 1.5rem;
    border-radius: 25px;
    font-weight: bold;
    text-decoration: none;
  }

  .logout-btn:hover {
    background: #c82333;
    text-decoration: none;
  }
</style>

<div class="dashboard-card">
  <h2>Welcome, Admin 👋</h2>
  <p>What would you like to do?</p>
  <a href="{% url 'create' %}" class="dashboard-btn">➕ Add Uploads</a>
    <a href="{% url 'announcement' %}" class="dashboard-btn">➕ Add Announcements</a>
  <a href="{% url 'uploadlist' %}" class="dashboard-btn">📝 Edit/Delete Uploads</a>
  <a href="{% url 'read' %}" class="dashboard-btn">📝 Edit/Delete Announcements</a>

  <!-- 🔒 Logout button only shown here -->
  <!-- <br>
  <a href="{% url 'logout' %}" class="logout-btn">🚪 Logout</a> -->
</div>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% block title %}
  <title>Ward 12 Dashboard</title>
  {% endblock %}

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet" />

  <style>
    html, body {
      margin: 0;
      padding: 0;
      height: 100%;
      display: flex;
      flex-direction: column;
      font-family: 'Segoe UI', sans-serif;
      background-color: rgba(239, 242, 245, 0.7);
    }

    main {
      flex: 1;
      display: flex;
      flex-direction: column;
    }

    .navbar {
      position: fixed;
      top: 0;
      width: 100%;
      z-index: 1000;
    }

    .main-section {
      flex: 1;
      display: flex;
      flex-direction: column;
      margin-top: 56px; /* navbar height */
      min-height: calc(100vh - 56px - 60px); /* full screen minus navbar and footer */
    }

    @media (min-width: 768px) {
      .main-section {
        flex-direction: row;
        width: 100%;
      }
    }

    .left-image, .right-image {
      flex: 1 1 50%;
      background-size: cover;
      background-position: center;
      position: relative;
      min-height: 50vh;
      min-width: 0;
    }

    .left-image {
      background-image: url('https://www.medicaldevice-network.com/wp-content/uploads/sites/23/2023/11/Shutterstock_1128043784.jpg');
    }

    .right-image {
      background-image: url('https://cdn.pixabay.com/photo/2022/12/19/06/57/stethoscope-7664837_640.jpg');
    }

    .text-overlay {
      position: absolute;
      top: 20px;
      left: 60%;
      transform: translateX(-50%);
      text-align: center;
      padding: 0.5rem 1.5rem;
      border-radius: 10px;
      animation: slideText 3s ease-in-out infinite alternate;
    }

    .text-overlay p {
      margin: 0;
      font-size: 1.5rem;
      font-weight: bold;
      color: hsl(190, 12%, 90%);
      text-shadow: 0 2px 5px rgba(0,0,0,0.5);
    }

    @keyframes slideText {
      0% { transform: translateX(-50%) translateY(0); }
      50% { transform: translateX(-50%) translateY(5px); }
      100% { transform: translateX(-50%) translateY(0); }
    }

    footer {
      background-color: #0998eb;
      color: white;
      text-align: center;
      padding: 1rem 0;
      font-weight: 500;
    }

    /* Sidebar styles */
    .sidebar {
      position: fixed;
      top: 56px; /* below navbar */
      right: -300px;
      width: 300px;
      height: calc(100% - 56px);
      background-color: #ffffff;
      overflow-y: auto;
      transition: right 0.3s ease;
      z-index: 1050;
      box-shadow: -2px 0 5px rgba(0,0,0,0.2);
    }

    .sidebar.open {
      right: 0;
    }

    .sidebar-header {
      background-color: #f8f9fa;
      border-bottom: 1px solid #ddd;
    }
  </style>
</head>
<body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-primary px-3">
    <div class="d-flex align-items-center">
      <i class="fa-solid fa-gauge text-white me-2"></i>
      <a class="navbar-brand mb-0 h1 text-white" href="#"><b>Ward 12 Dashboard</b></a>
    </div>
    <ul class="nav ms-auto">
      <li class="nav-item"><a class="nav-link active text-white" href="{% url 'home' %}">Home</a></li>
      <li class="nav-item"><a class="nav-link text-white" href="{% url 'login' %}">AdminLogin</a></li>
      <li class="nav-item"><a class="nav-link text-white" href="{% url 'uploadlist' %}">DailyUploads</a></li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'read' %}" onclick="">Announcements</a>
      </li>
{% block logout %}
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'logout' %}" onclick="">Logout</a>
      </li>
      {% endblock %}
    </ul>
  </nav>

  <!-- Sidebar -->
  <div id="announcementSidebar" class="sidebar bg-light shadow">
    <div class="sidebar-header d-flex justify-content-between align-items-center p-3">
      <h5 class="mb-0">Announcements</h5>
      <button type="button" class="btn-close" aria-label="Close" onclick="toggleSidebar()"></button>
    </div>
    <div class="p-3">
      <!-- Static sample announcements -->
      
      <!-- You can replace this with dynamic content using Django later -->
    </div>
  </div>

  <!-- Main Section -->
  <main>
    {% block content %}
    <div class="main-section">
      <div class="left-image">
        <div class="text-overlay">
          <p>Welcome To Ward 12 Dashboard</p>
        </div>
      </div>
      <div class="right-image"></div>
    </div>
    {% endblock %}
  </main>

  <!-- Footer -->
  <footer>
    <i class="text-white me-2">© 2025 Ward 12 Dashboard. All rights reserved.</i>
  </footer>

  <!-- Sidebar Toggle Script -->
  <script>
    function toggleSidebar() {
      const sidebar = document.getElementById('announcementSidebar');
      sidebar.classList.toggle('open');
    }
  </script>
</body>
</html>

myapp/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{item.Filetype}}</h1>
    <h1>{{item.File}}</h1>
</body>
</html>

myapp/templates/update.html
{% extends 'Adduploads.html' %}